program: sweep_train.py
method: bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  learning_rate:
    min: 0.0001
    max: 0.001
  optimizer:
    values: ["adam", "sgd"]
  epochs: 
    values: [5, 10, 15]
project: ssl-study
entity: wandb_fc